using System;
using System.Runtime.InteropServices;

namespace CSSDL.Events.Structures
{
    public enum ScanCode
    {
        Unknown = 0,

        A = 4,
        B = 5,
        C = 6,
        D = 7,
        E = 8,
        F = 9,
        G = 10,
        H = 11,
        I = 12,
        J = 13,
        K = 14,
        L = 15,
        M = 16,
        N = 17,
        O = 18,
        P = 19,
        Q = 20,
        R = 21,
        S = 22,
        T = 23,
        U = 24,
        V = 25,
        W = 26,
        X = 27,
        Y = 28,
        Z = 29,

        Num1 = 30,
        Num2 = 31,
        Num3 = 32,
        Num4 = 33,
        Num5 = 34,
        Num6 = 35,
        Num7 = 36,
        Num8 = 37,
        Num9 = 38,
        Num0 = 39,

        Return = 40,
        Escape = 41,
        Backspace = 42,
        Tab = 43,
        Space = 44,

        Minus = 45,
        Equals = 46,
        LeftBracket = 47,
        RightBracket = 48,
        Backslash = 49,
        NunusHash = 50,
        Semicolon = 51,
        Apostrophe = 52,
        Grave = 53,
        Comma = 54,
        Period = 55,
        Slash = 56,

        CapsLock = 57,

        F1 = 58,
        F2 = 59,
        F3 = 60,
        F4 = 61,
        F5 = 62,
        F6 = 63,
        F7 = 64,
        F8 = 65,
        F9 = 66,
        F10 = 67,
        F11 = 68,
        F12 = 69,

        PrintScreen = 70,
        ScrollLock = 71,
        Pause = 72,
        Insert = 73,
        Home = 74,
        PageUp = 75,
        Delete = 76,
        End = 77,
        PageDown = 78,
        Right = 79,
        Left = 80,
        Down = 81,
        Up = 82,

        NumLockClear = 83,
        KeypadDivide = 84,
        KeypadMultiply = 85,
        KeypadMinus = 86,
        KeypadPlus = 87,
        KeypadEnter = 88,
        Keypad1 = 89,
        Keypad2 = 90,
        Keypad3 = 91,
        Keypad4 = 92,
        Keypad5 = 93,
        Keypad6 = 94,
        Keypad7 = 95,
        Keypad8 = 96,
        Keypad9 = 97,
        Keypad0 = 98,
        KeypadPeriod = 99,

        NonusBackslash = 100,
        Application = 101,
        Power = 102,
        KeypadEquals = 103,
        F13 = 104,
        F14 = 105,
        F15 = 106,
        F16 = 107,
        F17 = 108,
        F18 = 109,
        F19 = 110,
        F20 = 111,
        F21 = 112,
        F22 = 113,
        F23 = 114,
        F24 = 115,
        Execute = 116,
        Help = 117,
        Menu = 118,
        Select = 119,
        Stop = 120,
        Again = 121,
        Undo = 122,
        Cut = 123,
        Copy = 124,
        Paste = 125,
        Find = 126,
        Mute = 127,
        VolumeUp = 128,
        VolumeDown = 129,
        LockingCapsLock = 130,
        LockingNumLock = 131,
        LockingScrollLock = 132,
        KeypadComma = 133,
        KeypadEqualsAS400 = 134,

        International1 = 135,
        International2 = 136,
        International3 = 137,
        International4 = 138,
        International5 = 139,
        International6 = 140,
        International7 = 141,
        International8 = 142,
        International9 = 143,
        Lang1 = 144,
        Lang2 = 145,
        Lang3 = 146,
        Lang4 = 147,
        Lang5 = 148,
        Lang6 = 149,
        Lang7 = 150,
        Lang8 = 151,
        Lang9 = 152,

        AltErase = 153,
        SysReq = 154,
        Cancel = 155,
        Clear = 156,
        Prior = 157,
        Return2 = 158,
        Separator = 159,
        Out = 160,
        Oper = 161,
        ClearAgain = 162,
        CrSel = 163,
        ExSel = 164,

        Keypad00 = 176,
        Keypad000 = 177,
        ThousandsSeparator = 178,
        DecimalSeparator = 179,
        CurrencyUnit = 180,
        CurrencySubUnit = 181,
        KeypadLeftParenthesis = 182,
        KeypadRightParenthesis = 183,
        KeypadLeftBrace = 184,
        KeypadRightBrace = 185,
        KeypadTab = 186,
        KeypadBackspace = 187,
        KeypadA = 188,
        KeypadB = 189,
        KeypadC = 190,
        KeypadD = 191,
        KeypadE = 192,
        KeypadF = 193,
        KeypadXOR = 194,
        KeypadPower = 195,
        KeypadPercent = 196,
        KeypadLess = 197,
        KeypadGreater = 198,
        KeypadAmpersand = 199,
        KeypadDblAmpersand = 200,
        KeypadVerticalBar = 201,
        KeypadDblVerticalBar = 202,
        KeypadColon = 203,
        KeypadHash = 204,
        KeypadSpace = 205,
        KeypadAt = 206,
        KeypadExclam = 207,
        KeypadMemStore = 208,
        KeypadMemRecall = 209,
        KeypadMemClear = 210,
        KeypadMemAdd = 211,
        KeypadMemSubtract = 212,
        KeypadMemMultiply = 213,
        KeypadMemDivide = 214,
        KeypadPlusMinus = 215,
        KeypadClear = 216,
        KeypadClearEntry = 217,
        KeypadBinary = 218,
        KeypadOctal = 219,
        KeypadDecimal = 220,
        KeypadHexadecimal = 221,

        LeftCtrl = 224,
        LeftShift = 225,
        LeftAlt = 226,
        LeftGUI = 227,
        RightCtrl = 228,
        RightShift = 229,
        RightAlt = 230,
        RightGUI = 231,

        Mode = 257,
        AudioNext = 258,
        AudioPrev = 259,
        AudioStop = 260,
        AudioPlay = 261,
        AudioMute = 262,
        MediaSelect = 263,
        WWW = 264,
        Mail = 265,
        Calculator = 266,
        Computer = 267,
        AppControlSearch = 268,
        AppControlHome = 269,
        AppControlBack = 270,
        AppControlForward = 271,
        AppControlStop = 272,
        AppControlRefresh = 273,
        AppControlBookmarks = 274,
        BrightnessDown = 275,
        BrightnessUp = 276,
        DisplaySwitch = 277,
        KeyboardIlluminationToggle = 278,
        KeyboardIlluminationDown = 279,
        KeyboardIlluminationUp = 280,
        Eject = 281,
        Sleep = 282,

        App1 = 283,
        App2 = 284,
        NumScanCodes = 512
    }

    public enum KeyCode
    {
        Unknown = 0,

        Return = '\r',
        Escape = '\x1B',
        Backspace = '\b',
        Tab = '\t',
        Space = ' ',
        Exclaim = '!',
        QuoteDbl = '"',
        Hash = '#',
        Percent = '%',
        Dollar = '$',
        Ampersand = '&',
        Quote = '\'',
        LeftParenthesis = '(',
        RightParenthesis = ')',
        Asterisk= '*',
        Plus = '+',
        Comma = ',',
        Minus = '-',
        Period = '.',
        Slash = '/',
        Num0 = '0',
        Num1 = '1',
        Num2 = '2',
        Num3 = '3',
        Num4 = '4',
        Num5 = '5',
        Num6 = '6',
        Num7 = '7',
        Num8 = '8',
        Num9 = '9',
        Colon = ':',
        Semicolon = ';',
        Less = '<',
        Equals = '=',
        Greater = '>',
        Question = '?',
        At = '@',
        /*
           Skip uppercase letters
         */
        LeftBracket = '[',
        Backslash = '\\',
        RightBracket = ']',
        Caret = '^',
        Underscore = '_',
        Backquote = '`',
        A = 'a',
        B = 'b',
        C = 'c',
        D = 'd',
        E = 'e',
        F = 'f',
        G = 'g',
        H = 'h',
        I = 'i',
        J = 'j',
        K = 'k',
        L = 'l',
        M = 'm',
        N = 'n',
        O = 'o',
        P = 'p',
        Q = 'q',
        R = 'r',
        S = 's',
        T = 't',
        U = 'u',
        V = 'v',
        W = 'w',
        X = 'x',
        Y = 'y',
        Z = 'z',

        CapsLock = ScanCode.CapsLock | 1 << 30,

        F1 = ScanCode.F1 | 1 << 30,
        F2 = ScanCode.F2 | 1 << 30,
        F3 = ScanCode.F3 | 1 << 30,
        F4 = ScanCode.F4 | 1 << 30,
        F5 = ScanCode.F5 | 1 << 30,
        F6 = ScanCode.F6 | 1 << 30,
        F7 = ScanCode.F7 | 1 << 30,
        F8 = ScanCode.F8 | 1 << 30,
        F9 = ScanCode.F9 | 1 << 30,
        F10 = ScanCode.F10 | 1 << 30,
        F11 = ScanCode.F11 | 1 << 30,
        F12 = ScanCode.F12 | 1 << 30,

        PrintScreen = ScanCode.PrintScreen | 1 << 30,
        ScrollLock = ScanCode.ScrollLock | 1 << 30,
        Pause = ScanCode.Pause | 1 << 30,
        Insert = ScanCode.Insert | 1 << 30,
        Home = ScanCode.Home | 1 << 30,
        PageUp = ScanCode.PageUp | 1 << 30,
        Delete = ScanCode.Delete | 1 << 30,
        End = ScanCode.End | 1 << 30,
        PageDown = ScanCode.PageDown | 1 << 30,
        Right = ScanCode.Right | 1 << 30,
        Left = ScanCode.Left | 1 << 30,
        Down = ScanCode.Down | 1 << 30,
        Up = ScanCode.Up | 1 << 30,

        NumLockClear = ScanCode.NumLockClear | 1 << 30,
        KeypadDivide = ScanCode.KeypadDivide | 1 << 30,
        KeypadMultiply = ScanCode.KeypadMultiply | 1 << 30,
        KeypadMinus = ScanCode.KeypadMinus | 1 << 30,
        KeypadPlus = ScanCode.KeypadPlus | 1 << 30,
        KeypadEnter = ScanCode.KeypadEnter | 1 << 30,
        Keypad1 = ScanCode.Keypad1 | 1 << 30,
        Keypad2 = ScanCode.Keypad2 | 1 << 30,
        Keypad3 = ScanCode.Keypad3 | 1 << 30,
        Keypad4 = ScanCode.Keypad4 | 1 << 30,
        Keypad5 = ScanCode.Keypad5 | 1 << 30,
        Keypad6 = ScanCode.Keypad6 | 1 << 30,
        Keypad7 = ScanCode.Keypad7 | 1 << 30,
        Keypad8 = ScanCode.Keypad8 | 1 << 30,
        Keypad9 = ScanCode.Keypad9 | 1 << 30,
        Keypad0 = ScanCode.Keypad0 | 1 << 30,
        KeypadPeriod = ScanCode.KeypadPeriod | 1 << 30,

        Application = ScanCode.Application | 1 << 30,
        Power = ScanCode.Power | 1 << 30,
        KeypadEquals = ScanCode.KeypadEquals | 1 << 30,
        F13 = ScanCode.F13 | 1 << 30,
        F14 = ScanCode.F14 | 1 << 30,
        F15 = ScanCode.F15 | 1 << 30,
        F16 = ScanCode.F16 | 1 << 30,
        F17 = ScanCode.F17 | 1 << 30,
        F18 = ScanCode.F18 | 1 << 30,
        F19 = ScanCode.F19 | 1 << 30,
        F20 = ScanCode.F20 | 1 << 30,
        F21 = ScanCode.F21 | 1 << 30,
        F22 = ScanCode.F22 | 1 << 30,
        F23 = ScanCode.F23 | 1 << 30,
        F24 = ScanCode.F24 | 1 << 30,
        Execute = ScanCode.Execute | 1 << 30,
        Help = ScanCode.Help | 1 << 30,
        Menu = ScanCode.Menu | 1 << 30,
        Select = ScanCode.Select | 1 << 30,
        Stop = ScanCode.Stop | 1 << 30,
        Again = ScanCode.Again | 1 << 30,
        Undo = ScanCode.Undo | 1 << 30,
        Cut = ScanCode.Cut | 1 << 30,
        Copy = ScanCode.Copy | 1 << 30,
        Paste = ScanCode.Paste | 1 << 30,
        Find = ScanCode.Find | 1 << 30,
        Mute = ScanCode.Mute | 1 << 30,
        VolumeUp = ScanCode.VolumeUp | 1 << 30,
        VolumeDown = ScanCode.VolumeDown | 1 << 30,
        KeypadComma = ScanCode.Comma | 1 << 30,
        KeypadEqualsAS400 = ScanCode.KeypadEqualsAS400 | 1 << 30,

        AltErase = ScanCode.AltErase | 1 << 30,
        SysReq = ScanCode.SysReq | 1 << 30,
        Cancel = ScanCode.Cancel | 1 << 30,
        Clear = ScanCode.Clear | 1 << 30,
        Prior = ScanCode.Prior | 1 << 30,
        Return2 = ScanCode.Return2 | 1 << 30,
        Separator = ScanCode.Separator | 1 << 30,
        Out = ScanCode.Out | 1 << 30,
        Oper = ScanCode.Oper | 1 << 30,
        ClearAgain = ScanCode.ClearAgain | 1 << 30,
        CrSel = ScanCode.CrSel | 1 << 30,
        ExSel = ScanCode.ExSel | 1 << 30,

        Keypad00 = ScanCode.Keypad00 | 1 << 30,
        Keypad000 = ScanCode.Keypad000 | 1 << 30,
        ThousandsSeparator = ScanCode.ThousandsSeparator | 1 << 30,
        DecimalSeparator = ScanCode.DecimalSeparator | 1 << 30,
        CurrencyUnit = ScanCode.CurrencyUnit | 1 << 30,
        CurrencySubUnit = ScanCode.CurrencySubUnit | 1 << 30,
        KeypadLeftParenthesis = ScanCode.KeypadLeftParenthesis | 1 << 30,
        KeypadRightParenthesis = ScanCode.KeypadRightParenthesis | 1 << 30,
        KeypadLeftBrace = ScanCode.KeypadLeftBrace | 1 << 30,
        KeypadRightBrace = ScanCode.KeypadRightBrace | 1 << 30,
        KeypadTab = ScanCode.KeypadTab | 1 << 30,
        KeypadBackspace = ScanCode.KeypadBackspace | 1 << 30,
        KeypadA = ScanCode.KeypadA | 1 << 30,
        KeypadB = ScanCode.KeypadB | 1 << 30,
        KeypadC = ScanCode.KeypadC | 1 << 30,
        KeypadD = ScanCode.KeypadD | 1 << 30,
        KeypadE = ScanCode.KeypadE | 1 << 30,
        KeypadF = ScanCode.KeypadF | 1 << 30,
        KeypadXOR = ScanCode.KeypadXOR | 1 << 30,
        KeypadPower = ScanCode.KeypadPower | 1 << 30,
        KeypadPercent = ScanCode.KeypadPercent | 1 << 30,
        KeypadLess = ScanCode.KeypadLess | 1 << 30,
        KeypadGreater = ScanCode.KeypadGreater | 1 << 30,
        KeypadAmpersand = ScanCode.KeypadAmpersand | 1 << 30,
        KeypadDblAmpersand = ScanCode.KeypadDblAmpersand | 1 << 30,
        KeypadVerticalBar = ScanCode.KeypadVerticalBar | 1 << 30,
        KeypadDblVerticalBar = ScanCode.KeypadDblVerticalBar | 1 << 30,
        KeypadColon = ScanCode.KeypadColon | 1 << 30,
        KeypadHash = ScanCode.KeypadHash | 1 << 30,
        KeypadSpace = ScanCode.Space | 1 << 30,
        KeypadAt = ScanCode.KeypadAt | 1 << 30,
        KeypadExclam = ScanCode.KeypadExclam | 1 << 30,
        KeypadMemStore = ScanCode.KeypadMemStore | 1 << 30,
        KeypadMemRecall = ScanCode.KeypadMemRecall | 1 << 30,
        KeypadMemClear = ScanCode.KeypadMemClear | 1 << 30,
        KeypadMemAdd = ScanCode.KeypadMemAdd | 1 << 30,
        KeypadMemSubtract = ScanCode.KeypadMemSubtract | 1 << 30,
        KeypadMemMultiply = ScanCode.KeypadMemMultiply | 1 << 30,
        KeypadMemDivide = ScanCode.KeypadMemDivide | 1 << 30,
        KeypadPlusMinus = ScanCode.KeypadPlusMinus | 1 << 30,
        KeypadClear = ScanCode.KeypadClear | 1 << 30,
        KeypadClearEntry = ScanCode.KeypadClearEntry | 1 << 30,
        KeypadBinary = ScanCode.KeypadBinary | 1 << 30,
        KeypadOctal = ScanCode.KeypadOctal | 1 << 30,
        KeypadDecimal = ScanCode.KeypadDecimal | 1 << 30,
        KeypadHexadecimal = ScanCode.KeypadHexadecimal | 1 << 30,

        LeftCtrl = ScanCode.LeftCtrl | 1 << 30,
        LeftShift = ScanCode.LeftShift | 1 << 30,
        LeftAlt = ScanCode.LeftAlt | 1 << 30,
        LeftGUI = ScanCode.LeftGUI | 1 << 30,
        RightCtrl = ScanCode.RightCtrl | 1 << 30,
        RightShift = ScanCode.RightShift | 1 << 30,
        RightAlt = ScanCode.RightAlt | 1 << 30,
        RightGUI = ScanCode.RightGUI | 1 << 30,

        Mode = ScanCode.Mode | 1 << 30,

        AudioNext = ScanCode.AudioNext | 1 << 30,
        AudioPrev = ScanCode.AudioPrev | 1 << 30,
        AudioStop = ScanCode.AudioStop | 1 << 30,
        AudioPlay = ScanCode.AudioPlay | 1 << 30,
        AudioMute = ScanCode.AudioMute | 1 << 30,
        MediaSelect = ScanCode.MediaSelect | 1 << 30,
        WWW = ScanCode.WWW | 1 << 30,
        Mail = ScanCode.Mail | 1 << 30,
        Calculator = ScanCode.Calculator | 1 << 30,
        Computer = ScanCode.Computer | 1 << 30,
        AppControlSearch = ScanCode.AppControlSearch | 1 << 30,
        AppControlHome = ScanCode.AppControlHome | 1 << 30,
        AppControlBack = ScanCode.AppControlBack | 1 << 30,
        AppControlForward = ScanCode.AppControlForward | 1 << 30,
        AppControlStop = ScanCode.AppControlStop | 1 << 30,
        AppControlRefresh = ScanCode.AppControlRefresh | 1 << 30,
        AppControlBookmarks = ScanCode.AppControlBookmarks | 1 << 30,

        BrightnessDown = ScanCode.BrightnessDown | 1 << 30,
        BrightnessUp = ScanCode.BrightnessUp | 1 << 30,
        DisplaySwitch = ScanCode.DisplaySwitch | 1 << 30,
        KeyboardIlluminationToggle = ScanCode.KeyboardIlluminationToggle | 1 << 30,
        KeyboardIlluminationDown = ScanCode.KeyboardIlluminationDown | 1 << 30,
        KeyboardIlluminationUp = ScanCode.KeyboardIlluminationUp | 1 << 30,
        Eject = ScanCode.Eject | 1 << 30,
        Sleep = ScanCode.Sleep | 1 << 30,
    }

    public enum KeyModifier : UInt16
    {
        None = 0x0000,
        LeftShift = 0x0001,
        RightShift = 0x0002,
        Shift = 0x0003,
        LeftCtrl = 0x0040,
        RightCtrl = 0x0080,
        Ctrl = 0x00C0,
        LeftAlt = 0x0100,
        RightAlt = 0x0200,
        Alt = 0x0300,
        LeftGUI = 0x0400,
        RightGUI = 0x0800,
        GUI = 0x0C00,
        Num = 0x1000,
        Caps = 0x2000,
        Mode = 0x4000,
        Reserved = 0x8000
    }

    [StructLayout(LayoutKind.Sequential)]
    public struct Key
    {
        public ScanCode ScanCode { get; }
        public KeyCode KeyCode { get; }
        public KeyModifier Modifiers { get; }
    }
}
